### ISSUE TITLE
Sometimes some frames can't be decoded even with accessing by file://

### ISSUE THREAD

**Issue by Javernaut** [Javernaut/WhatTheCodec#1]

**Comment by Kyant0** [comment]
Is it a permission issue? If so, I suggest you use a custom AvIoContext that uses FILE * as stream. Open a file descriptor in Java and open file in jni. Jni doesn't always have permission to access files by path, even if you granted reading permission in Java.

**Comment by Javernaut** [comment]
In near future I'll reexamine all the protocols that are applicable in Android, including the case with permissions. At least this is planned in my private Jira :)

**Comment by Javernaut** [comment]
Closing as this one is superseded by another ticket in private jira.
