### ISSUE TITLE
Play video with it

### ISSUE THREAD

**Issue by mamour666** [Javernaut/WhatTheCodec#5]
Can this be used to play video and decoding video like mkv which is not natively supported by android i mean ffmpeg android maker sorry?

**Comment by Javernaut** [comment]
Hello.

Well, the ffmpeg-android-maker does support mkv decoding. The WhatTheCodec app doesn't use any native android decoding.
So yes, it is possible to decode and display frames from a mkv container using ffmpeg-android-maker.

**Comment by mamour666** [comment]
Hello thank for that script and explanation the script work very well and  i successfull build ffmpeg android maker today.But the function getFrameBitmap() return me an error (Overload resolution ambiguity: public open fun containsKey(key: Int): Boolean defined in java.util.HashMap
public open fun containsKey(key: Int!): Boolean defined in java.util.HashMap)
 when i compile the whatthecodec app .i have tried to resoleve it by myself without success

**Comment by Javernaut** [comment]
Closing as stale.
