### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by smoil-ali** [Javernaut/WhatTheCodec#8]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libswresample.so" not found

**Comment by Javernaut** [comment]
@smoil-ali The issue you are having now is neither a problem of the WhatTheCodec app nor of the ffmpeg-android-maker.

If you just googled this problem you would know that the shared library isn't packaged to the final APK. Please refer to my articles and look for CMakeLists.txt and build.gradle - there is the info for packaging .so files.

Please stop creating issues for whatever problems you face and moreover - duplicating them in all my repositories. The way you talk does not favor the helping you.
