### ISSUE TITLE
cannot get the library from Maven

### ISSUE THREAD

**Issue by kminlee** [Javernaut/WhatTheCodec#9]
Hi.
I get the following error x 7 times.
Do I have to put the user login and password for github.com? If so, how please?

K-MIn

Execution failed for task ':app:checkAmazonDebugAarMetadata'.
> Could not resolve all files for configuration ':app:amazonDebugRuntimeClasspath'.
   > Could not resolve com.javernaut.mediafile:mediafile:1.0.0.
     Required by:
         project :app
      > Could not resolve com.javernaut.mediafile:mediafile:1.0.0.
         > Could not get resource 'https://maven.pkg.github.com/Javernaut/MediaFile/com/javernaut/mediafile/mediafile/1.0.0/mediafile-1.0.0.pom'.
            > Could not GET 'https://maven.pkg.github.com/Javernaut/MediaFile/com/javernaut/mediafile/mediafile/1.0.0/mediafile-1.0.0.pom'. Received status code 400 from server: Bad Request

**Comment by Javernaut** [comment]
Hello @kminlee ,

This thing is that I'm currently migrating the library to Maven Central. And I use Github Packages as a playground for now. It will be ditched after the migration.

Meanwhile you can use [this commit](https://github.com/Javernaut/WhatTheCodec/tree/8240d6d8a2abc33797fcf385d364705c87ac16f3) where the library wasn't extracted, but you will have to do certain setup on your own. Or just wait a little bit. I'm finishing the migration already.

**Comment by Javernaut** [comment]
@kminlee 

The MediaFile library is finally migrated to Maven Central. The master branch of WhatTheCodec is now [compilablle](https://github.com/Javernaut/WhatTheCodec/actions/runs/1159580778).
